crm/crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import path, include
from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')), # All urls that begin with dashboard will be handled by dashboard/urls.py
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('about/', about, name='about'),
    path('login/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/lead/urls.py
from django.urls import path

from .import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.leads_export, name='export'),
]

crm/lead/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team

# Create your models here.
class Lead(models.Model):
    #checking what priority this lead has
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
    )

    #Making it possible to change the status of the lead
    NEW = 'new '
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        ('NEW', 'New'),
        ('CONTACTED', 'Contacted'),
        ('WON', 'Won'),
        ('LOST', 'Lost'),
    )

    #Creating the fields for the lead
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modifeid_at = models.DateTimeField(auto_now=True) # Everytime we save this db model it will be automatically updated

    class Meta:
        ordering = ('name',)
        
    def __str__(self):
        return self.name

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='lead_files')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

crm/lead/forms.py
from django import forms
from .models import Comment, Lead, LeadFile

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status')

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400', 
            'placeholder': 'Comment'
            })
        )

class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

    file = forms.CharField(
        widget=forms.FileInput(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400'
            })
        )

crm/lead/views.py
import csv
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Lead
from django.http import HttpResponse
from django.contrib import messages
from django.views import View
from team.models import Team
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from .forms import AddCommentForm, AddFileForm
from client.models import Client, Comment as ClientComment

# Create your views here.
# Using class based views rather than function based views

@login_required
def leads_export(request):
    leads = Lead.objects.filter(created_by=request.user)

    #creating the Httpresponse object with the appropriate csv header

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="leads.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Client', 'Description', 'Created By', 'Created At'])

    #looping through all the clients
    for lead in leads:
        writer.writerow([lead.name, lead.description, lead.created_by, lead.created_at])

    return response

class LeadListView(LoginRequiredMixin, ListView): # list based view for leads list
    model = Lead
    
    #Using class based views - loginRequiredMixin instead of the decorator login_required

    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, converted_to_client=False)

class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] =  AddCommentForm()
        context['filesform'] = AddFileForm()

        return context
    
    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')
    
    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status')
    success_url = reverse_lazy('leads:list')
    
    def get_context_data(self, **kwargs):
        context = super(LeadUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit Lead'

        return context
    
    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status')
    success_url = reverse_lazy('leads:list')
    
    def get_context_data(self, **kwargs):
        context = super(LeadCreateView, self).get_context_data(**kwargs)
        team = self.request.user.userprofile.active_team
        context['team'] = team
        context['title'] = 'Add Lead'

        return context

    def form_valid(self, form):

        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.active_team
        self.object.save()

        return redirect(self.get_success_url())

class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.lead_id = pk
            file.team = self.request.user.userprofile.active_team
            file.created_by = request.user
            file.save()

        return redirect('leads:detail', pk=pk)

class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = self.request.user.userprofile.active_team
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)
    
class ConvertToClientView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        lead = get_object_or_404(Lead, created_by=request.user, pk=self.kwargs.get('pk'))
        team = self.request.user.userprofile.active_team
        
        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team=team,
        )
        
        lead.converted_to_client = True
        lead.save()

        #converting lead comments to client comments

        comments = lead.comments.all()

        for comment in comments:
            ClientComment.objects.create(
                content=comment.content,
                created_by=comment.created_by,
                team=comment.team,
                client=client,
            )

        #success message and redirect

        messages.success(request, 'Lead converted to client successfully')

        return redirect('leads:list')

crm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{lead.name}}{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">{{lead.name}}</h1>

        {% if lead.description %}
            <p class="px-6 font-semibold">Name</p>
            <p class="px-6 mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="px-6 font-semibold">Priority</p>
        <p class="px-6 mb-2">{{ lead.get_priority_display }}</p>

        <p class="px-6 font-semibold">Status</p>
        <p class="px-6 mb-2">{{ lead.get_status_display }}</p>

        <p class="px-6 font-semibold">Created at</p>
        <p class="px-6 mb-2">{{ lead.created_at|date:"M-d-Y H:i" }}</p>

        <p class="px-6 font-semibold">Modified at</p>
        <p class="px-6 mb-6">{{ lead.modified_at }}</p>

        <hr class="my-4">

        <form id="lead_delete_form" action="{% url 'leads:delete' lead.id %}"  method="POST">
            {% csrf_token %}
        </form>

        <div class="px-6">
            <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Convert to client</a>
            <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Edit</a>
            <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>

            <hr class="my-4">

            <h2 class="mb-6 text-xl">Comments</h2>

            <div class="space-y-4">
                {% for comment in lead.comments.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ comment.created_by }}</strong>@ {{ comment.created_at }}</p>
                        {{ comment.content }}
                    </div>
                {% endfor %}
            </div>

            <br>
            <form action="{% url 'leads:add_comment' lead.id %}" method="POST">
                {% csrf_token %}

                {{ form.as_p }}

                <br>
                <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
            </form>
        </div>

        <hr class="my-4">
        <div class="px-6">
            <h2 class="mb-6 text-xl">Files</h2>

            <div class="space-y-4">
                {% for file in lead.files.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ file.created_by }}</strong>@ {{ file.created_at }}</p>
                        
                        <button class="py-2 px-4 rounded-xl bg-sky-500 text-white"><a href="{{ file.file.url }}" target="_blank">Download</a></button>

                    </div>
                {% endfor %}
            </div>

            <form action="{% url 'leads:add_file' lead.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ filesform.as_p }}

                <br>
                <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
            </form>
        </div>

        <hr class="my-4">

        <div class="px-6">
            <a href="{% url 'leads:list' %}">Back to Leads</a>
        </div>
        <hr class="my-4">
    </div>
{% endblock %}

crm/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div>
        <h1 class="text-xl p-6">{{ title }}</h1>

        {% if team.plan.max_leads > team.leads.count or title == 'Edit Lead' %}
        <!-- checking how many leads we have for this team -->
        <!-- Total Leads: {{ team.leads.all|length }} -->
            <form action="." method="POST" class="mx-8">
                {% csrf_token %}
                
                Name:
                <div class="mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400">
                    {{ form.name }}
                  </div>
                  Email:
                  <div class="mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400">
                    {{ form.email }}
                  </div>
                  Description:
                  <div class="mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400">
                    {{ form.description }}
                  </div>
                  Priority:
                  <div class="mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400">
                    {{ form.priority }}
                  </div>
                  Status:
                  <div class="mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400">
                    {{ form.status }}
                  </div>

                <hr class="mb-3">
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">
                    Submit
                </button>
            </form>
        {% else %}
            <div class="mt-6 mb-6 px-10 py-4 bg-red-400 rounded-xl text-white">
                You've reached the maximum number of leads. Upgrade your plan!
            </div>
        {% endif %}

    </div> 
{% endblock %}

crm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">Leads</h1>

        <div class="px-4">
            <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 text-white rounded-xl">Add Lead</a>
            <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Export leads</a>
        </div>
        
        {% if object_list %}
        
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-6 bg-gray-200 font-semibold w-full">Name</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        </div>

        {% for lead in object_list %}
            <div class="flex justify-between">
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">
                   <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a> 
                </p>
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
            </div>   
            {% endfor %}
        {% else %}
        <p class="mt-6 px-2 text-center">No leads found!</p>
        {% endif %}
    </div>
{% endblock %}

crm/lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}{{lead.name}}{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">{{lead.name}}</h1>

        {% if lead.description %}
            <p class="px-6 font-semibold">Name</p>
            <p class="px-6 mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="px-6 font-semibold">Priority</p>
        <p class="px-6 mb-2">{{ lead.get_priority_display }}</p>

        <p class="px-6 font-semibold">Status</p>
        <p class="px-6 mb-2">{{ lead.get_status_display }}</p>

        <p class="px-6 font-semibold">Created at</p>
        <p class="px-6 mb-2">{{ lead.created_at|date:"M-d-Y H:i" }}</p>

        <p class="px-6 font-semibold">Modified at</p>
        <p class="px-6 mb-6">{{ lead.modified_at }}</p>

        <hr class="my-4">

        <div class="px-6">
            <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Convert to client</a>
            <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Edit</a>
            <a href="{% url 'leads:delete' lead.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>
        </div>

        <hr class="my-4">

        <div class="px-6">
            <a href="{% url 'leads:list' %}">Back to Leads</a>
        </div>
        <hr class="my-4">
    </div>
{% endblock %}

crm/lead/templates/lead/leads_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">Leads</h1>

        <div class="px-4">
            <a href="{% url 'leads:add_lead' %}" class="inline-block py-4 px-6 bg-teal-600 text-white rounded-xl">Add Lead</a>
        </div>

        {% if leads %}
        
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-6 bg-gray-200 font-semibold w-full">Name</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        </div>

        {% for lead in leads %}
            <div class="flex justify-between">
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">
                   <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a> 
                </p>
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
            </div>   
            {% endfor %}
        {% else %}
        <p class="mt-6 px-2 text-center">No leads found!</p>
        {% endif %}
    </div>
{% endblock %}