crm/client/urls.py
from django.urls import path
from .import views

app_name = 'clients' #Adding name spaces to all the apps

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('add/', views.clients_add, name='add'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/add-comment', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file', views.clients_add_file, name='add_file'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('export/', views.clients_export, name='export'),
]

crm/crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import path, include
from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')), # All urls that begin with dashboard will be handled by dashboard/urls.py
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('about/', about, name='about'),
    path('login/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/client/models.py
from django.contrib.auth.models import User
from django.db import models
from team.models import Team #One reference for the team to each of the other models

# Create your models here.
class Client(models.Model):
    #Creating the fields for the lead
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modifeid_at = models.DateTimeField(auto_now=True) # Everytime we save this db model it will be automatically updated

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='client_files')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

crm/client/forms.py
from django import forms
from .models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description')

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400', 
            'placeholder': 'Name'
            })
        )
    email = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400', 
            'placeholder': 'Email'
            })
        )
    description = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400', 
            'placeholder': 'Description'
            })
        )

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400', 
            'placeholder': 'Comment'
            })
        )

class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)
    
    file = forms.CharField(
        widget=forms.FileInput(attrs={
            'class': 'form-control mb-6 my-4 w-full py-4 px-6 rounded-xl bg-gray-100 border border-gray-200 placeholder-gray-500 focus:outline-none focus:border-gray-400'
            })
        )

crm/client/views.py
import csv
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import AddClientForm, AddCommentForm, AddFileForm
from django.contrib import messages
from team.models import Team

# Create your views here.

@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    #creating the Httpresponse object with the appropriate csv header

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(['Client', 'Description', 'Created By', 'Created At'])

    #looping through all the clients
    for client in clients:
        writer.writerow([client.name, client.description, client.created_by, client.created_at])

    return response

@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)

    return render(request, "client/clients_list.html", {"clients": clients})

@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.created_by = request.user
            file.client_id = pk
            file.save()

            return redirect('clients:detail', pk=pk)
        return redirect('clients:detail', pk=pk)

@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
    else:
        form = AddCommentForm()

    return render(request, "client/clients_detail.html", {
        'client': client,
        'form': form,
        'filesform': AddFileForm(),
    })


@login_required
def clients_add(request):
    team = request.user.userprofile.active_team
    if request.method == "POST":
        form = AddClientForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, "Client added successfully")

            return redirect("clients:list")
    else:
        form = AddClientForm()

    return render(request, "client/clients_add.html", {
        "form": form,
        'team': team,
    })


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)
        
        if form.is_valid():
            form.save()

            messages.success(request, 'Client updated successfully')

            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)
    
    return render(request, 'client/clients_edit.html', {
        'form': form
    })


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, "Client deleted successfully")

    return redirect("clients:list")

crm/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Add client{% endblock %}

{% block content %}
    <div>
        <h1 class="mt-6 px-6 text-xl">Add Client</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            <form action="." method="POST" class="p-6">
                {% csrf_token %}

                {{ form.as_p }}

                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">
                    Submit
                </button>
            </form>
        {% else %}
            <div class="mt-6 mb-6 px-10 py-4 bg-red-400 rounded-xl text-white">
                You've reached the maximum number of clients. Upgrade your plan!
            </div>
        {% endif %}
    </div> 
{% endblock %}

crm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{client.name}}{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">{{client.name}}</h1>

        {% if client.description %}
            <p class="px-6 font-semibold">Description</p>
            <p class="px-6 mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="px-6 font-semibold">Created at</p>
        <p class="px-6 mb-2">{{ client.created_at|date:"M-d-Y H:i" }}</p>

        <p class="px-6 font-semibold">Modified at</p>
        <p class="px-6 mb-6">{{ client.modified_at }}</p>

        <hr class="my-4">

        <div class="px-6">
            
            <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Edit</a>
            <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>
        </div>

        <hr class="my-4">

        <div class="px-6">
            <h2 class="mb-6 text-xl">Comments</h2>

            <div class="space-y-4">
                {% for comment in client.comments.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ comment.created_by }}</strong>@ {{ comment.created_at }}</p>
                        {{ comment.content }}
                    </div>
                {% endfor %}
            </div>

            <br>
            <form action="{% url 'clients:add_comment' client.id %}" method="POST" >

                {% csrf_token %}

                {{ form.as_p }}

                <br>
                <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
            </form>
        </div>

        <hr class="my-4">
        <div class="px-6">
            <h2 class="mb-6 text-xl">Files</h2>

            <div class="space-y-4">
                {% for file in client.files.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ client.created_by }}</strong>@ {{ client.created_at }}</p>
                        
                        <button class="py-2 px-4 rounded-xl bg-sky-500 text-white"><a href="{{ file.file.url }}" target="_blank">Download</a></button>

                    </div>
                {% endfor %}
            </div>

            <form action="{% url 'clients:add_file' client.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ filesform.as_p }}

                <br>
                <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
            </form>
        </div>

        <hr class="my-4">

        <div class="px-6">
            <a href="{% url 'clients:list' %}">Back to Clients</a>
        </div>
        <hr class="my-4">
    </div>
{% endblock %}

crm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit client{% endblock %}

{% block content %}
    <div>
        <h1 class="text-xl p-6">Edit Client</h1>

        <form action="." method="POST" class="p-6">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">
                Submit
            </button>
        </form>
    </div> 
{% endblock %}

crm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}Clients{% endblock %}

{% block content %}
    <div>
        <h1 class="px-6 mt-4 mb-4 text-xl">Clients</h1>

        <div class="px-4">
            <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 text-white rounded-xl">Add Client</a>
            <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Export clients</a>
        </div>

        {% if clients %}
        
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-6 bg-gray-200 font-semibold w-full">Name</p>
        </div>

        {% for client in clients %}
            <div class="flex justify-between">
                <p class="py-2 px-6 w-full {% cycle 'bg-gray-100' '' %}">
                   <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a> 
                </p>
            </div>   
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2 text-center">No clients found!</p>
        {% endif %}
    </div>
{% endblock %}